#include <algorithm>
#include <filesystem>
#include <fstream>
#include <string>
#include <vector>

namespace fs = std::filesystem;

int main() {
    const fs::path lib_dir = "lib";
    const fs::path out_path = fs::path("include") / "all_libs_generated.h";

    if (!fs::exists(lib_dir)) {
        return 1;
    }

    std::vector<std::string> cpp_files;
    for (const auto& entry : fs::directory_iterator(lib_dir)) {
        if (!entry.is_regular_file()) {
            continue;
        }
        const fs::path path = entry.path();
        if (path.extension() != ".cpp") {
            continue;
        }
        const std::string name = path.filename().string();
        if (name == "module_registry.cpp" || name == "builtins_registry.cpp") {
            continue;
        }
        cpp_files.push_back(name);
    }

    std::sort(cpp_files.begin(), cpp_files.end());

    std::ofstream out(out_path);
    if (!out) {
        return 1;
    }

    out << "// Generated by tools/gen_all_libs.cpp\n";
    out << "#ifndef ALL_LIBS_GENERATED_H\n";
    out << "#define ALL_LIBS_GENERATED_H\n\n";
    for (const auto& name : cpp_files) {
        out << "#include \"../lib/" << name << "\"\n";
    }
    out << "#include \"../lib/builtins_registry.cpp\"\n\n";
    out << "#endif\n";
    return 0;
}
